"""Deterministic Markdown report for a closed backtest.

Reads ``backtest_runs.metrics`` (frozen JSON) and aggregates per-persona.
Buy-and-hold baseline is approximated from the benchmark stored alongside
each backtest_runs row.

Reproducibility property: same backtest_id → same Markdown output
*except* a single ``generated_ts:`` header line.
"""

from __future__ import annotations

import json
import sqlite3
import statistics
from datetime import datetime, timezone
from typing import Dict, List


def render_report(conn: sqlite3.Connection, *, backtest_id: int) -> str:
    bt = conn.execute(
        "SELECT * FROM backtests WHERE backtest_id = ?", (backtest_id,)
    ).fetchone()
    if bt is None:
        raise ValueError(f"backtest_id {backtest_id} not found")
    universe = json.loads(bt["universe"])

    rows = list(conn.execute(
        "SELECT persona_id, ticker, metrics FROM backtest_runs "
        "WHERE backtest_id = ? ORDER BY persona_id, ticker",
        (backtest_id,),
    ))

    by_persona: Dict[str, List[dict]] = {}
    errored: List[dict] = []
    for r in rows:
        m = json.loads(r["metrics"])
        m["_persona_id"] = r["persona_id"]
        m["_ticker"] = r["ticker"]
        if m.get("status") == "errored":
            errored.append(m)
        elif m.get("status") == "closed":
            by_persona.setdefault(r["persona_id"], []).append(m)

    lines: List[str] = []
    lines.append(f"# F2 Backtest Report #{backtest_id}")
    lines.append("")
    lines.append(f"generated_ts: {datetime.now(timezone.utc).isoformat()}")
    lines.append("")
    lines.append(f"- **Universe:** {', '.join(universe)}")
    lines.append(f"- **Start date:** {bt['start_date']}")
    lines.append(f"- **End date:**   {bt['end_date']}")
    lines.append(f"- **Status:**     {bt['status']}")
    if bt["triggered_by_brief_id"]:
        lines.append(f"- **Triggered by brief:** `{bt['triggered_by_brief_id']}`")
    lines.append("")

    # Per-persona aggregate
    lines.append("## Per-persona aggregate")
    lines.append("")
    lines.append("| Persona | Sharpe | Total Return | Alpha | Win Rate | N |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for persona_id in sorted(by_persona):
        items = by_persona[persona_id]
        sharpe = _mean([m["sharpe"] for m in items])
        total = _mean([m["total_return"] for m in items])
        alpha = _mean([m["alpha"] for m in items])
        winrt = _mean([m["win_rate"] for m in items])
        lines.append(
            f"| {persona_id} | {sharpe:+.3f} | {total:+.4f} | {alpha:+.4f} | "
            f"{winrt:.3f} | {len(items)} |"
        )
    lines.append("")

    # Buy-and-hold baseline (from benchmark_return — same window).
    lines.append("## Buy-and-hold baseline")
    lines.append("")
    bench_rets = [m["benchmark_return"]
                   for items in by_persona.values()
                   for m in items
                   if m.get("benchmark_return") is not None]
    if bench_rets:
        avg_bench = _mean(bench_rets)
        lines.append(f"- Average benchmark return over window: {avg_bench:+.4f}")
    else:
        lines.append("- Benchmark return unavailable for all rows.")
    lines.append("")

    # Per-ticker detail
    lines.append("## Per-(persona, ticker) detail")
    lines.append("")
    lines.append("| Persona | Ticker | Decision | Entry | Exit | Total Return | Alpha | Sharpe |")
    lines.append("|---|---|---|---:|---:|---:|---:|---:|")
    for persona_id in sorted(by_persona):
        for m in by_persona[persona_id]:
            lines.append(
                f"| {persona_id} | {m['_ticker']} | {m['decision']} | "
                f"{m['entry_price']:.2f} | {m['exit_price']:.2f} | "
                f"{m['total_return']:+.4f} | {m['alpha']:+.4f} | {m['sharpe']:+.3f} |"
            )
    lines.append("")

    if errored:
        lines.append("## Errored rows")
        lines.append("")
        for m in errored:
            lines.append(
                f"- {m['_persona_id']} × {m['_ticker']}: {m.get('error', '(no message)')}"
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by `tradingagents.backtest.report`.*")
    return "\n".join(lines)


def _mean(xs):
    return statistics.fmean(xs) if xs else 0.0
